version: 0.2
phases:
  install:
    commands:
    - echo "entered build phase new"
    finally:
    - echo "entered install phase new"
  pre_build:
    commands:
    - echo "entered build phase new"
    finally:
    - echo "entered pre build phase new"
  build:
    commands:
    - echo "entered build phase new"
    finally:
    - echo "entered build build phase new"
  post_build: 
    commands:
    - echo "enterd the post build phase new"
    finally:
    - echo "entered post build phase new"

